version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - DATABASE_CONNECTION_STRING=Host=postgres;Database=teslastarter;Username=teslastarter;Password=teslastarter123!
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: teslastarter
      POSTGRES_PASSWORD: teslastarter123!
      POSTGRES_DB: teslastarter
    ports:
      - "5432:5432"

  seq:
    image: datalust/seq:latest
    restart: unless-stopped
    volumes:
      - seq-data:/data
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:5341"  # Ingestion port
      - "8081:80"    # Web UI port

volumes:
  postgres-data:
  seq-data: